### ISSUE TITLE
add_worms error, unclear usage

### ISSUE THREAD

**Issue by stsmall** [stsmall/mda_models_scripts#18]
Traceback (most recent call last):
  File "testable_run.py", line 238, in <module>
    dfHost, dfAdult, dfJuv, dfMF= wb_sims(10, '../tests/wbsims.cfg')
  File "testable_run.py", line 205, in wb_sims
    dfMF)
  File "build/bdist.linux-x86_64/egg/figs/transmissionKDtree.py", line 252, in transmission_fx
  File "build/bdist.linux-x86_64/egg/figs/worm.py", line 44, in add_worms
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2961, in reset_index
    new_obj.insert(0, name, values)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2449, in insert
    allow_duplicates=allow_duplicates)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 3510, in insert
    raise ValueError('cannot insert %s, already exists' % item)
ValueError: cannot insert level_0, already exists

**Comment by stsmall** [comment]
fixed by adding drop=True
