### ISSUE TITLE
transmission error, rare

### ISSUE THREAD

**Issue by stsmall** [stsmall/mda_models_scripts#43]
Traceback (most recent call last):
  File "testable_run.py", line 274, in <module>
    seed, model = wb_sims('../tests/wbsims.cfg')
  File "testable_run.py", line 205, in wb_sims
    L3transdict)
  File "build/bdist.linux-x86_64/egg/figs/transmissionKDtree.py", line 256, in transmission_fx
    new_hostidx.append(dfHost.ix[rehostidx,'hostidx'])
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 84, in __getitem__
    return self._getitem_tuple(key)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 796, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 922, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1032, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 102, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 1779, in xs
    loc = self.index.get_loc(key)
  File "/home/scott/anaconda2/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8564)
  File "pandas/src/hashtable_class_helper.pxi", line 410, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8508)
KeyError: 146

**Comment by stsmall** [comment]
dfHost was not indexed properly, no idea why this was happening.
